CREATE VIEW MEMENTOSCRAPERDATABASE.`MEMENTOS_VW` AS
SELECT MENTO.PHRASE,
    MENTO.OWNER,
    MENTO.COMMENT,
    MENTO.TYPE AS SOCIAL_TYPE, 
    MEM.URL,
    MEM.MEDIA_TYPE
FROM MEMENTOSCRAPERDATABASE.MEMENTOS MENTO
INNER JOIN MEMENTOSCRAPERDATABASE.MEMORIES MEM ON MENTO.ID = MEM.MementoForeignKey;